# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [4]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/izmr3/anaconda3/Library/include
    lib directory: C:/Users/izmr3/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
Z=np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize)) #%d

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
numpy.info(numpy.add)
#%run `python -c "import numpy; numpy.info(numpy.add)"`

NameError: name 'numpy' is not defined

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
Z=np.arange(10,50)#49以下ではなく50未満
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
Z=np.arange(50)
Z=Z[::-1]#?
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
Z=np.arange(0,9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
Z=np.eye(3)#eyeとは？
print(Z,"\n")
Z=np.identity(3)
print(Z)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [11]:
Z = np.random.random(10)#×randam
Z.sort()
print(Z)

[0.04820293 0.15533827 0.47575507 0.56249292 0.62157462 0.72075883
 0.87775341 0.90390295 0.93000953 0.96205635]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [12]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [14]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)#//,false,Z[0]=1
Z.flags.writeable=True#?
Z[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
#### 44. デカルト座標を表すランダムな 10x2 行列を考え、極座標に変換します (★★☆)

In [21]:
Z = np.random.random((10,2))#(10,2)
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.09500151 0.85361397 0.43785849 1.0097164  0.89083277 0.84105541
 0.08527763 0.67749554 1.13766125 0.78878946]
[1.0154474  0.93467788 0.4536367  0.24234587 0.09089504 1.54387901
 1.16319925 0.01677113 0.69788352 1.08058667]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [22]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.5531967  0.8350767  0.         0.28518279 0.05092933 0.07546042
 0.51161823 0.90023147 0.04514573 0.72137153]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
#### 46. [0,1]x[0,1] 領域をカバーする `x` および `y` 座標を含む構造化配列を作成します (★★☆)

In [24]:
Z = np.zeros((5,5),[('x',float),('y',float)])
#np.linspace(2,10,5)は初項2,最大項10,項数5の等差数列
Z['x'],Z['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))#spase
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
#### 47. 2 つの配列 X と Y を指定して、コーシー列 (収束値は分からないが収束することが分かる列)C (Cij =1/(xi - yj)) を構築します (★★☆)

In [25]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X,Y)#減算，外側
print(np.linalg.det(C))#?線形代数（Linear algebra）

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
#### 48. 各 numpy スカラー型の表現可能な最小値と最大値を出力します (★★☆)

In [31]:
for dtype in[np.int8,np.int32,np.int64]:#numpy.iinfo()で整数，numpy.finfo()で浮動小数点数の情報を得る
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in[np.float32,np.float64]:
    print(np.finfo(dtype).min)    
    print(np.finfo(dtype).max)    
    print(np.finfo(dtype).eps)#?何故エラー？
"""for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)"""

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


'for dtype in [np.int8, np.int32, np.int64]:\n   print(np.iinfo(dtype).min)\n   print(np.iinfo(dtype).max)\nfor dtype in [np.float32, np.float64]:\n   print(np.finfo(dtype).min)\n   print(np.finfo(dtype).max)\n   print(np.finfo(dtype).eps)'

#### 49. How to print all the values of an array? (★★☆)

In [32]:
np.set_printoptions(threshold=float("inf"))#print()で表示するときの設定,threshold:しきい値
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [33]:
Z = np.random.random(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()#argmin()は配列の最小値のインデックスを取得するもの.argument of the maximum(最大値を与える引数)の略
print(Z[index])

0.9976633721669097


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [39]:
Z = np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])#"""1とは？"""
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\izmr3\AppData\Local\Temp\ipykernel_5232\2726824099.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])#"""1とは？"""


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 52. 座標を表す形状 (100,2) のランダム ベクトルを考慮し、点ごとの距離 (★★☆) を求めます。

In [40]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2+(Y-Y.T)**2)#Y.Tとは。転置。
print(D)

[[0.         0.68958636 0.41943257 1.10725875 1.03127524 0.96812842
  0.38802609 0.63579016 0.32680154 0.82105794 0.58956962 0.58246097
  0.6740599  0.501138   0.48018701 0.66574316 0.60867356 0.79046211
  0.56790119 0.41861658 0.3268229  0.95198708 0.29697324 0.85816937
  0.3862187  0.81516071 0.5705774  0.13583844 0.75837266 0.45538725
  0.20642937 0.31521741 0.2268246  0.47782137 0.42394727 0.44011001
  0.33948763 0.72351361 0.28002993 0.59029033 0.40784719 0.67409055
  0.47717788 0.40598096 0.29212526 0.97592386 0.50144161 0.09840152
  0.63235967 0.43763016 0.76171985 0.28544139 0.90234714 0.41812678
  0.69406577 0.14794218 0.7564222  0.73191332 0.82321243 0.43681481
  0.47529364 0.90843391 0.24575989 0.20060565 0.25664225 0.93871915
  0.51801763 0.62638735 1.02378811 1.01939977 0.50121365 0.42477817
  0.85896669 0.03983684 0.74372131 0.61073943 0.80767042 0.74902003
  0.95823235 0.44592457 0.77866521 0.35430877 0.47782997 0.45245684
  0.70805012 0.68941334 0.97117612 0.43245602 0.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [42]:
Z = (np.random.rand(10)*100).astype(np.float32)#(配列Z) = (ランダムな小数値配列rand(10))×100 → (データ型float32に変換)
Y = Z.view(np.int32)#(配列Y) = (配列Z)を(データ型int32)として解釈するビュー
Y[:] =  Z
print(Y)#np.random.dand(3,2)の引数は数値。np.random.random((3,2))の引数は配列。np.reros((3,2))の引数は配列。np.ones((3,2))の引数は配列。

[41 32 67 26 39 58 60 14 95 99]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO#(モジュールioからStringIOクラス)をインポート
#ioモジュールには、入出力操作（ファイルの読み書きなど）を扱う便利なツールがたくさん定義されています
#StringIO**は、Pythonのioモジュールの一部で、文字列を「ファイルのように扱う」ためのクラス

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 55. numpy 配列の enumerate(列挙する) に相当するものは何ですか? (★★☆)

In [47]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):"""np.ndenumerate() は、多次元配列を走査して各要素の インデックス と 値 を取得"""
    print(index,value)#N-dimensional (N次元),enumerate (列挙する)
for index in np.ndindex(Z.shape):#np.ndindex() は、多次元配列の形状（ここでは (3, 3)）を基に、すべてのインデックスを生成
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [50]:
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma,mu = 1.0, 0.0
G = np.exp(-((D-mu)**2/(2.0*sigma**2)))#正規分布関数
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [52]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace= False),1)#(ランダムな位置に1を配置する)： (Zの要素番号配列の中から、ランダムにp個選ぶ) → (その位置に1を代入)
#range(n*n):「(ゼロからn*n-1までの連続した整数のリスト)」
#np.random.choice(range(n*n), p, replace=False):「(インデックス範囲range(n*n)の中から、ランダムにp個選ぶ（重複なし）)」
#np.put(Z, ...(...は省略の記号), 1):「(2次元配列Zをフラットにした状態で、指定したインデックスに1を代入する)」配列 Z に、選ばれたランダムな位置に値 1 を設定する。
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
np.random.rand(5,10)#andom,5.10。5×10の行列
Y = X - X.mean(axis=1,keepdims=True)#X.mean(axis=1, keepdims=True)各行の平均値を計算し、結果を配列 X と同じ形状に保つ
#配列 X から対応する行の平均値を引き、行方向で中心化された配列 Y を作成。
Y = X - X.mean(axis=1).reshape(-1,1)#X.mean(axis=1):各行の平均値を計算する。
#.reshape(-1, 1):上記の1次元配列を、5行1列の縦長の配列に変形する。
#-1 は「残りのサイズを自動で計算してください」という意味
print(Y)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


#### 59. How to sort an array by the nth column? (★★☆)

#### 59. 配列を n 番目の列でソートするにはどうすればよいですか? (★★☆)

In [ ]:
N = np.random.randint(0,10,(3,3))#0以上10未満の整数をランダムに生成して、3×3の配列 N を作成
N = np.random.randint(0, 10, (3, 3))
print(Z)#出力結果が01?
#print(Z[:,1].argsort())#配列Nの2列目N[:, 1])の昇順ソート順を取得(argsort())

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
#null:0
Z = np.random.randint(0,3,(3,10))#要素が2まで
print((~Z.any(axis=0)).any())#Z.any(axis=0):配列 Z の各列ごとに「少なくとも1つの非ゼロ要素があるか」を確認。
#any(axis=0) は「列方向」での評価?
#~ はブール値を反転

#null:np.nan
Z = np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
"""Zの中身は、[[0.0, 1.0, nan],
 [1.0, 2.0, nan],
 [4.0, 5.0, nan]]
 nanはNot a Numberで未定義の値や欠損値"""
print(np.isnan(Z).all(axis=0))#np.isnan(Z):配列 Z の各要素が NaN かどうかを判定.結果は、同じ形状のブール配列。
#.all(axis=0):配列の各列ごとに「すべての要素が True か」を判定。

False
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)#(下限、上限、行列の形)0 から 1 の間で一様分布に従うランダムな浮動小数点数を生成し、それを長さ10の1次元配列として Z に格納
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print(m)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [64]:
A = np.arange(3).reshape(3,1)#縦ベクトル
B = np.arange(3).reshape(1,3)#横ベクトル
it = np.nditer([A,B,None])#A:配列1,B:配列2、None:出力配列→A,Bは3×3行列に
#nd :n次元、iter:iteratorイテレータ
for x,y,z in it:
    z[...]=x+y#空行列z.「...」:エリプシス。全ての次元を指定する際に使う。
print(it.operands[2])#it.operands[2]:np.nditer に指定された3つ目の配列（None）が結果配列として使われているので、これが最終結果
#Operand (オペランド): 演算の対象となる値や変数

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 63. name属性(★★☆)を持つ配列クラスを作成する

In [ ]:
#Z = np.array((10,10),['name',str])
class NamedArray(np.ndarray):#NamedArray は、NumPy の ndarray を拡張したクラス
    def __new__(cls,array,name="no name"):#__new__ は、インスタンス化時に呼ばれる特別なメソッド
        obj = np.asarray(array).view(cls)#NumPy 配列をクラス NamedArray のインスタンスに変換し、name 属性を設定します
        #array を NumPy 配列に変換。as~はデータ型を変換。
        #ビュー（参照）
        obj.name = name
        return obj
    def __array_finalize__(self,obj):#__array_finalize__ は、NumPy 配列の派生オブジェクトが生成されたときに呼ばれます
        if obj is None: 
            return#改行しても、改行しなくてもいい。
        self.name = getattr(obj,'name',"no name")#親オブジェクト（obj）から name 属性を取得し、それを新しいオブジェクトに引き継ぎます

Z = NamedArray(np.arange(10),"ranege_10")#配列 Z の名前は "range_10" に設定
print(Z.name)

ranege_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
#### 64. 与えられたベクトルについて考えます。2 番目のベクトルによってインデックス付けされた各要素に 1 を加算する方法 (インデックスの繰り返しには注意してください)。 (★★★)

In [ ]:
Z = np.ones(10)#長さ10の横ベクトル
I = np.random.randint(0,len(Z),20)#0 から len(Z)-1 の範囲でランダムな整数を 20 個生成
Z += np.bincount(I,minlength=len(Z))#I の中で出現するインデックスごとにその出現回数を数える。
#出現回数を Z の長さに合わせて調整。
#bincountとは、「ビン箱＋カウント＝区分けして分類する箱」
print(Z)

[2. 2. 1. 6. 4. 3. 3. 5. 1. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
#### インデックスリスト (I) に基づいて、ベクトル (X) の要素を配列 (F) に累積する方法は？

In [ ]:
X = [1,2,3,4,5,6]#元のデータ。蓄積したい値。
I = [1,3,9,3,4,1]#インデックスリスト。どのインデックスに対応するか。
F = np.bincount(I,X)#F[I[i]]=X[i]数えているわけではなく、足している。例：F[1]=1+6=7
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
#### 66. (dtype=ubyte) の (w,h,3) 画像を考慮して、一意の色の数を計算します (★★☆)

In [ ]:
w,h = 255,256
I = np.random.randint(0,4,(h,w,3)).astype(np.ubyte)#()の中の場合は3次元。np.random.randint(0, 4, (h, w, 3)): 0 から 3 までの整数をランダムに生成して、画像の高さ h と幅 w に合わせた h x w x 3 の形状の配列を作成
#.astype(np.ubyte) は、この配列のデータ型を np.uint8（符号なし8ビット整数）に変換。
colors = np.unique(I.reshape(-1,3),axis=0)#rexhape
#np.unique()値がユニークな行だけを返す。
#I.reshape(-1, 3) は、I の3次元配列（(h, w, 3)）を、1次元に変換します。具体的には、画像内のすべてのピクセルのRGB値を1行にまとめた形に変換します。この形状は (h * w, 3)
#-1:残りの次元を自動的に計算して調整して
#np.unique(I.reshape(-1, 3), axis=0) は、RGBの値がユニークな行だけを返します。
n = len(colors)#colors には、画像内でユニークな色が格納されているので、len(colors) はその色の数を返します。これが画像に含まれているユニークな?色の数
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
#### 67. 4 次元の配列を考慮して、最後の 2 つの軸の合計を一度に取得するにはどうすればよいですか? (★★★)

In [ ]:
# 3次元配列Aを生成。形状は(3, 4, 3, 4)で、要素は0から9の整数のランダムな値
A = np.random.randint(0, 10, (3, 4, 3, 4))

# sum関数を使って、最後の2軸（-2と-1軸）に沿って合計を計算
# axis=(-2, -1) は、Aの4番目と3番目の次元を指定して、その次元ごとに合計を取る
# axis:軸
sum = A.sum(axis=(-2, -1))  # 形状が(3, 4)の合計を得る
print(sum)

# Aの形状を変更して、最後の2つの次元を1つにまとめる
# reshapeで、Aの形状を(3, 4, -1)に変換、最後の次元を1つの軸にまとめる
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)  # axis=-1 は、新しい最後の軸に沿って合計を計算
print(sum)


[[49 57 61 51]
 [58 50 57 53]
 [69 53 37 50]]
[[49 57 61 51]
 [58 50 57 53]
 [69 53 37 50]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
#### 68. 1 次元ベクトル D を考えると、サブセットのインデックスを記述する同じサイズのベクトル S を使用して D のサブセットの平均を計算するにはどうすればよいでしょうか? (★★★)

In [84]:
D = np.random.uniform(0, 1, 100)   # 0 から 1 の間でランダムに浮動小数点数を 100 個生成
S = np.random.randint(0, 10, 100)   # 0 から 9 の間でランダムに整数を 100 個生成
#0,1,100,int,unintは存在しない。
D_sums = np.bincount(S,weights=D)
# S の値に基づいて D の加重合計を計算（D の各値が S のインデックスごとに合計される）
D_sums = np.bincount(S, weights=D)

# S の値に基づいて D の個数（出現回数）をカウント
D_counts = np.bincount(S)
#bincounts、（）なし
# 各インデックスごとに D_sums を D_counts で割って平均を計算
D_means = D_sums / D_counts

# 結果を表示
print(D_means)


[0.56748955 0.44912953 0.34451433 0.48787255 0.42745029 0.53078335
 0.44842879 0.46388152 0.49627194 0.36975161]


#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)